suila/login/urls.py
# SPDX-FileCopyrightText: 2024 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0

from typing import List

from django.urls import URLPattern, URLResolver, include, path
from django.views.generic import TemplateView
from django_mitid_auth.saml.views import AccessDeniedView
from login.views import (  # BeskLoginCallbackView,; BeskMitIDLoginView,
    BeskLoginView,
    LogoutView,
    MitIdErrorView,
    TwoFactorSetup,
)

app_name = "login"


urlpatterns: List[URLResolver | URLPattern] = [
    # path("mitid/login/", BeskMitIDLoginView.as_view(), name="login"),
    # path(
    #     "mitid/login/callback/", BeskLoginCallbackView.as_view(),
    #      name="login-callback"
    # ),
    path("mitid/", include("django_mitid_auth.urls", namespace="mitid")),
    path(
        "login",
        BeskLoginView.as_view(),
        name="login",
    ),
    path(
        "logout",
        LogoutView.as_view(),
        name="logout",
    ),
    path(
        "error/login-timeout/",
        AccessDeniedView.as_view(template_name="login/login_timeout.html"),
        name="login-timeout",
    ),
    path(
        "error/login-repeat/",
        AccessDeniedView.as_view(template_name="login/login_repeat.html"),
        name="login-repeat",
    ),
    path(
        "error/login-nocpr/",
        AccessDeniedView.as_view(template_name="login/login_no_cpr.html"),
        name="login-no-cpr",
    ),
    path(
        "error/login-mitid-error/",
        MitIdErrorView.as_view(),
        name="login-mitid-error",
    ),
    path(
        "error/login-failed/",
        AccessDeniedView.as_view(template_name="login/login_failed.html"),
        name="login-failed",
    ),
    path(
        "logged_out",
        TemplateView.as_view(template_name="login/logged_out.html"),
        name="logged_out",
    ),
    path("two_factor/setup", TwoFactorSetup.as_view(), name="two_factor_setup"),
]

suila/login/forms.py
# SPDX-FileCopyrightText: 2024 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0

from common.form_mixins import BootstrapForm
from django import forms
from django.conf import settings
from django.contrib.auth.forms import AuthenticationForm as DjangoAuthenticationForm
from django.contrib.auth.forms import UsernameField
from django.forms import CharField, PasswordInput, TextInput
from django.utils.translation import gettext_lazy as _
from two_factor.forms import AuthenticationTokenForm


class AuthenticationForm(BootstrapForm, DjangoAuthenticationForm):
    username = UsernameField(
        label=_("Brugernavn"),
        widget=TextInput(
            attrs={
                "autofocus": True,
                "class": "form-control",
                "placeholder": _("Brugernavn"),
            }
        ),
    )
    password = CharField(
        label=_("Password"),
        strip=False,
        widget=PasswordInput(
            attrs={
                "autocomplete": "current-password",
                "class": "form-control",
                "placeholder": _("Kodeord"),
            }
        ),
    )

    error_messages = {
        "invalid_login": _(
            "Indtast venligst korrekt brugernavn og adgangskode. "
            "Bemærk, at begge felter kan være versalfølsomme."
        ),
        "inactive": _("Denne konto er inaktiv."),
    }


class BeskAuthenticationTokenForm(AuthenticationTokenForm):
    def __init__(self, user, initial_device, **kwargs):
        """
        Overwritten to set a Danish label on the `remember` field.
        """
        super().__init__(user, initial_device, **kwargs)
        self.fields["remember"] = forms.BooleanField(
            required=False,
            initial=True,
            label=_("Husk mig på denne maskine i {days} dage").format(
                days=int(settings.TWO_FACTOR_REMEMBER_COOKIE_AGE / 3600 / 24)
            ),
        )

suila/login/views.py
# SPDX-FileCopyrightText: 2024 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0

from common.utils import add_parameters_to_url
from django.conf import settings
from django.contrib.auth import (
    BACKEND_SESSION_KEY,
    REDIRECT_FIELD_NAME,
    authenticate,
    login,
    logout,
)
from django.contrib.auth.views import redirect_to_login
from django.http import HttpRequest, HttpResponse
from django.http.response import HttpResponseForbidden, HttpResponseNotFound
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import RedirectView
from login.forms import AuthenticationForm, BeskAuthenticationTokenForm
from two_factor.views import LoginView, SetupView


class BeskLoginView(LoginView):
    AUTH_STEP = "auth"
    TOKEN_STEP = "token"

    form_list = (
        (AUTH_STEP, AuthenticationForm),
        (TOKEN_STEP, BeskAuthenticationTokenForm),
    )

    def get_form_list(self):
        form_list = super().get_form_list()

        # In case we wish to bypass 2FA we should never go to the token step.
        if settings.BYPASS_2FA and self.TOKEN_STEP in form_list:
            del form_list[self.TOKEN_STEP]

        return form_list

    def done(self, form_list, **kwargs):
        redir = self.get_success_url()
        user = self.get_user()
        if redir.startswith("/admin") and not (user.is_staff or user.is_superuser):
            return HttpResponseForbidden(
                "You do not have permission to access this page."
            )
        return super().done(form_list, **kwargs)

    def get_form(self, step=None, data=None, files=None):
        """
        Returns the form for the step. Overwritten because the default method hard-codes
        the form for the token-step as AuthenticationTokenForm instead of
        BeskAuthenticationTokenForm
        """
        if step is None:
            step = self.steps.current

        form_class = self.get_form_list()[step]
        kwargs = self.get_form_kwargs(step)
        kwargs.update(
            {
                "data": data,
                "files": files,
                "prefix": self.get_form_prefix(step, form_class),
                "initial": self.get_form_initial(step),
            }
        )

        return form_class(**kwargs)

    def get_success_url(self):
        return self.back or reverse("suila:root")

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            if settings.PUBLIC:
                # MitID login
                response = self.login_mitid(request, *args, **kwargs)
            else:
                # django login
                response = self.login_django(request, *args, **kwargs)
            if response:
                if self.back:
                    response.set_cookie(
                        "back",
                        self.back,
                        secure=True,
                        httponly=True,
                        samesite="None",
                    )
                return response

        backpage = self.request.COOKIES.get("back")
        if backpage:
            return redirect(backpage)
        return redirect("suila:root")

    def login_mitid(self, request, *args, **kwargs) -> HttpResponse | None:
        # Get user from auth data
        user = authenticate(
            request=request,
            saml_data=request.session.get("saml"),
        )
        if user and user.is_authenticated:
            # store user in session
            login(
                request=request,
                user=user,
                backend="django_mitid_auth.saml.backend.Saml2Backend",
            )
        if not request.user.is_authenticated:
            # no user, redirect to login page
            return redirect(reverse("login:mitid:login"))
        return None

    def login_django(self, request, *args, **kwargs) -> HttpResponse | None:
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **context):
        return super().get_context_data(
            **{
                **context,
                "back": self.back,
            }
        )

    @property
    def back(self):
        return self.request.GET.get("back") or self.request.GET.get(REDIRECT_FIELD_NAME)


class TwoFactorSetup(SetupView):
    form_list = [("method", BeskAuthenticationTokenForm)]

    def dispatch(self, request, *args, **kwargs):
        if settings.PUBLIC:
            return HttpResponseNotFound()
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return add_parameters_to_url(
            reverse("suila:root"),
            {"two_factor_success": 1},
        )


class LogoutView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        if settings.PUBLIC and (
            self.request.session.get(BACKEND_SESSION_KEY)
            == "django_mitid_auth.saml.backend.Saml2Backend"
            or "saml" in self.request.session
        ):
            return reverse("login:mitid:logout")
        else:
            logout(self.request)
            return settings.LOGOUT_REDIRECT_URL


def on_session_expired(request: HttpRequest) -> HttpResponse | None:
    if request.path == reverse("login:mitid:logout-callback"):
        return None  # Do not redirect to login
    redirect_url = getattr(settings, "SESSION_TIMEOUT_REDIRECT", None)
    if redirect_url:
        return redirect(redirect_url)
    else:
        return redirect_to_login(next=request.path)

suila/login/templates/login/logged_out.html
{# SPDX-FileCopyrightText: 2025 Magenta ApS <info@magenta.dk> #}
{# SPDX-License-Identifier: MPL-2.0 #}

{% extends "common/card.html" %}
{% load i18n %}

{% block title %}
{% translate "Logget ud" %}
{% endblock %}

{% block content %}
<p>{% translate "Du er nu logget ud. Vi anbefaler, at du lukker denne fane for at slette eventuelle tilbageværende data." %}</p>
<a href="{% url 'login:login' %}" class="btn btn-primary">{% translate "Log in" %}</a>
{% endblock %}

suila/login/templates/login/login_failed.html
{# SPDX-FileCopyrightText: 2025 Magenta ApS <info@magenta.dk> #}
{# SPDX-License-Identifier: MPL-2.0 #}

{% extends "common/card.html" %}
{% load i18n %}

{% block title %}
{% translate "Login mislykkedes" %}
{% endblock %}

{% block userinfo %}
{% endblock %}

{% block content %}
    {% translate "Adgang nægtet" as header %}
    {% translate 'Der kunne ikke logges ind med den angivne bruger.' as body %}
    <h1>{{ header }}</h1>
    <p>{{ body }}</p>
    <a class="btn btn-primary" href="{% url 'login:logout' %}">{% translate 'Log ud' %}</a>
{% endblock %}

suila/login/templates/login/login_mitid_error.html
{# SPDX-FileCopyrightText: 2025 Magenta ApS <info@magenta.dk> #}
{# SPDX-License-Identifier: MPL-2.0 #}

{% extends "common/card.html" %}
{% load i18n %}

{% block title %}
{% translate "Adgang nægtet" %}
{% endblock %}

{% block userinfo %}
{% endblock %}

{% block content %}
    {% translate "Adgang nægtet" as header %}
    {% translate 'Vi oplever problemer med MitID. Prøv igen senere.' as body %}
    <h1>{{ header }}</h1>
    <p>{{ body }}</p>
{% endblock %}

suila/login/templates/login/login_no_cpr.html
{# SPDX-FileCopyrightText: 2025 Magenta ApS <info@magenta.dk> #}
{# SPDX-License-Identifier: MPL-2.0 #}

{% extends "common/card.html" %}
{% load i18n %}

{% block title %}
{% translate "Adgang nægtet" %}
{% endblock %}

{% block userinfo %}
{% endblock %}

{% block content %}
    {% translate "Adgang nægtet" as header %}
    {% translate 'Det anvendte login har ikke et CPR-nummer tilknyttet.' as body %}
    <h1>{{ header }}</h1>
    <p>{{ body }}</p>
    <a class="btn btn-primary" href="{% url 'login:logout' %}">{% translate 'Log ud' %}</a>
{% endblock %}

suila/login/templates/login/login_repeat.html
{# SPDX-FileCopyrightText: 2025 Magenta ApS <info@magenta.dk> #}
{# SPDX-License-Identifier: MPL-2.0 #}

{% extends "common/card.html" %}
{% load i18n %}

{% block title %}
{% translate "Adgang nægtet" %}
{% endblock %}

{% block userinfo %}
{% endblock %}

{% block content %}
    {% translate "Adgang nægtet" as header %}
    {% translate 'Det anvendte login er allerede anvendt. Prøv at logge ind igen.' as body %}
    <h1>{{ header }}</h1>
    <p>{{ body }}</p>
    <a class="btn btn-primary" href="{% url 'login:login' %}">{% translate 'Log ind' %}</a>
{% endblock %}

suila/login/templates/login/login_timeout.html
{# SPDX-FileCopyrightText: 2025 Magenta ApS <info@magenta.dk> #}
{# SPDX-License-Identifier: MPL-2.0 #}

{% extends "common/card.html" %}
{% load i18n %}

{% block title %}
{% translate "Adgang nægtet" %}
{% endblock %}

{% block userinfo %}
{% endblock %}

{% block content %}
    {% translate "Adgang nægtet" as header %}
    {% translate 'Det anvendte login er timet ud. Prøv at logge ind igen.' as body %}
    <h1>{{ header }}</h1>
    <p>{{ body }}</p>
    <a class="btn btn-primary" href="{% url 'login:login' %}">{% translate 'Log ind' %}</a>
{% endblock %}