suila/login/urls.py
# SPDX-FileCopyrightText: 2024 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0

from typing import List

from django.urls import URLPattern, URLResolver, include, path
from django.views.generic import TemplateView
from django_mitid_auth.saml.views import AccessDeniedView
from login.views import (  # BeskLoginCallbackView,; BeskMitIDLoginView,
    BeskLoginView,
    LogoutView,
    MitIdErrorView,
    TwoFactorSetup,
)

app_name = "login"


urlpatterns: List[URLResolver | URLPattern] = [
    # path("mitid/login/", BeskMitIDLoginView.as_view(), name="login"),
    # path(
    #     "mitid/login/callback/", BeskLoginCallbackView.as_view(),
    #      name="login-callback"
    # ),
    path("mitid/", include("django_mitid_auth.urls", namespace="mitid")),
    path(
        "login",
        BeskLoginView.as_view(),
        name="login",
    ),
    path(
        "logout",
        LogoutView.as_view(),
        name="logout",
    ),
    path(
        "error/login-timeout/",
        AccessDeniedView.as_view(template_name="login/login_timeout.html"),
        name="login-timeout",
    ),
    path(
        "error/login-repeat/",
        AccessDeniedView.as_view(template_name="login/login_repeat.html"),
        name="login-repeat",
    ),
    path(
        "error/login-nocpr/",
        AccessDeniedView.as_view(template_name="login/login_no_cpr.html"),
        name="login-no-cpr",
    ),
    path(
        "error/login-mitid-error/",
        MitIdErrorView.as_view(),
        name="login-mitid-error",
    ),
    path(
        "error/login-failed/",
        AccessDeniedView.as_view(template_name="login/login_failed.html"),
        name="login-failed",
    ),
    path(
        "logged_out",
        TemplateView.as_view(template_name="login/logged_out.html"),
        name="logged_out",
    ),
    path("two_factor/setup", TwoFactorSetup.as_view(), name="two_factor_setup"),
]

suila/suila/urls.py
# SPDX-FileCopyrightText: 2024 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0

from typing import List

from django.urls import URLPattern, URLResolver, path

from suila.api import api
from suila.views import (
    CalculationParametersGraph,
    CalculationParametersListView,
    CalculatorView,
    EboksMessageView,
    EmbeddingTemplateView,
    GeneratedEboksMessageView,
    GraphView,
    PersonAnnualIncomeEstimateUpdateView,
    PersonDetailEboksPreView,
    PersonDetailEboksSendView,
    PersonDetailIncomeView,
    PersonDetailNotesAttachmentView,
    PersonDetailNotesView,
    PersonDetailView,
    PersonGraphView,
    PersonPauseListView,
    PersonPauseUpdateView,
    PersonSearchView,
    PersonTaxScopeHistoryView,
    PersonYearEstimationEngineUpdateView,
    RootView,
)

app_name = "suila"


urlpatterns: List[URLResolver | URLPattern] = [
    path("api/", api.urls, name="api"),
    path("", RootView.as_view(), name="root"),
    path("calculator/", CalculatorView.as_view(), name="calculator"),
    path("graph/", GraphView.as_view(), name="graph"),
    path(
        "faq/",
        EmbeddingTemplateView.as_view(template_name="suila/faq.html"),
        name="faq",
    ),
    path(
        "about/",
        EmbeddingTemplateView.as_view(template_name="suila/about.html"),
        name="about",
    ),
    path("persons/", PersonSearchView.as_view(), name="person_search"),
    path(
        "persons/forced_pause/",
        PersonPauseListView.as_view(),
        name="person_pause_overview",
    ),
    path("persons/<int:pk>/", PersonDetailView.as_view(), name="person_detail"),
    path("persons/<int:pk>/graph/", PersonGraphView.as_view(), name="person_graph"),
    path(
        "person_year/<int:pk>/engine/update",
        PersonYearEstimationEngineUpdateView.as_view(),
        name="update_estimation_engine",
    ),
    path(
        "persons/<int:pk>/income/",
        PersonDetailIncomeView.as_view(),
        name="person_detail_income",
    ),
    path(
        "persons/<int:pk>/notes/",
        PersonDetailNotesView.as_view(),
        name="person_detail_notes",
    ),
    path(
        "persons/<int:pk>/tax_scope_history/",
        PersonTaxScopeHistoryView.as_view(),
        name="person_tax_scope_history",
    ),
    path(
        "person/<int:pk>/pause/",
        PersonPauseUpdateView.as_view(),
        name="pause_person",
    ),
    path(
        "person/<int:pk>/set_annual_income/",
        PersonAnnualIncomeEstimateUpdateView.as_view(),
        name="set_person_annual_income_estimate",
    ),
    path(
        "note_attachments/<int:pk>/",
        PersonDetailNotesAttachmentView.as_view(),
        name="note_attachment",
    ),
    path(
        "persons/<int:pk>/eboks/",
        PersonDetailEboksPreView.as_view(),
        name="person_detail_eboks_preview",
    ),
    path(
        "persons/<int:pk>/eboks/send/",
        PersonDetailEboksSendView.as_view(),
        name="person_detail_eboks_send",
    ),
    path(
        "persons/<int:pk>/msg/<int:year>/<int:month>/<str:type>/",
        GeneratedEboksMessageView.as_view(),
        name="person_generated_message",
    ),
    path(
        "persons/<int:pk>/msg/",
        EboksMessageView.as_view(),
        name="person_existing_message",
    ),
    path(
        "calculation_parameters/",
        CalculationParametersListView.as_view(),
        name="calculation_parameters_list",
    ),
    path(
        "calculation_parameters/graph/",
        CalculationParametersGraph.as_view(),
        name="calculation_parameters_graph",
    ),
]

suila/suila/views.py
# SPDX-FileCopyrightText: 2024 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0
import itertools
import json
import logging
from dataclasses import dataclass
from datetime import date
from decimal import Decimal
from functools import cached_property
from math import ceil
from typing import Any, Iterable
from urllib.parse import urlencode

from common.fields import CPRField
from common.models import User
from common.utils import SuilaJSONEncoder, omit
from common.view_mixins import BaseGetFormView, ViewLogMixin
from dateutil.relativedelta import relativedelta
from django import forms
from django.conf import settings
from django.contrib import messages
from django.core.files.base import ContentFile
from django.core.management import call_command
from django.db import transaction
from django.db.models import CharField, F, IntegerChoices, QuerySet, Value
from django.db.models.functions import Cast, LPad
from django.forms.models import BaseInlineFormSet, fields_for_model, model_to_dict
from django.http import Http404, HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from django.template.defaultfilters import date as format_date
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.utils.formats import number_format
from django.utils.translation import gettext
from django.utils.translation import gettext_lazy as _
from django.utils.translation import gettext_noop, override
from django.views.decorators.clickjacking import xframe_options_sameorigin
from django.views.generic import DetailView, FormView, ListView, TemplateView
from django.views.generic.base import ContextMixin
from django.views.generic.detail import BaseDetailView
from django.views.generic.edit import UpdateView
from django_filters import Filter, FilterSet
from django_filters.views import FilterView
from django_tables2 import (
    BooleanColumn,
    Column,
    SingleTableMixin,
    Table,
    TemplateColumn,
)
from django_tables2.columns.linkcolumn import BaseLinkColumn
from django_tables2.utils import Accessor
from login.view_mixins import LoginRequiredMixin

from suila.data import engine_choices
from suila.dates import get_pause_effect_date, get_payment_date
from suila.forms import (
    CalculationParametersForm,
    CalculatorForm,
    ConfirmationForm,
    IncomeSignalFilterForm,
    NoteAttachmentFormSet,
    NoteForm,
    PauseForm,
    PersonAnnualIncomeEstimateForm,
    PersonYearEstimationEngineForm,
)
from suila.integrations.eboks.client import EboksClient
from suila.models import (
    BTaxPayment,
    Employer,
    IncomeType,
    ManagementCommands,
    MonthlyIncomeReport,
    Note,
    NoteAttachment,
    PauseReasonChoices,
    Person,
    PersonMonth,
    PersonYear,
    StandardWorkBenefitCalculationMethod,
    SuilaEboksMessage,
    TaxInformationPeriod,
    WorkingTaxCreditCalculationMethod,
    Year,
)
from suila.view_mixins import MustHavePersonYearMixin, PermissionsRequiredMixin

logger = logging.getLogger(__name__)


class RootView(LoginRequiredMixin, ViewLogMixin, TemplateView):
    template_name = "suila/root.html"

    def get(self, request, *args, **kwargs):
        self.log_view()
        return super().get(request, *args, **kwargs)


class NameColumn(BaseLinkColumn):
    def __init__(self, *args, **kwargs):
        linkify = dict(viewname="suila:person_detail", args=[Accessor("pk")])
        kwargs.setdefault("linkify", linkify)
        super().__init__(*args, **kwargs)


class PersonTable(Table):
    name = NameColumn(verbose_name=_("Navn"))
    cpr = Column(
        accessor=Accessor("_cpr"),
        order_by=Accessor("_cpr"),
        verbose_name=_("CPR-nummer"),
        orderable=False,
        linkify=dict(viewname="suila:person_detail", args=[Accessor("pk")]),
    )
    full_address = Column(verbose_name=_("Adresse"))


class PersonPauseTable(Table):
    name = NameColumn(verbose_name=_("Navn"))
    cpr = Column(
        verbose_name=_("CPR-nummer"),
        orderable=True,
    )
    allow_pause = BooleanColumn(
        verbose_name=_("Må selv genoptage udbetalinger"),
        orderable=True,
    )
    pause_start_date = Column(
        verbose_name=_("Startdato for udbetalingspause"),
        empty_values=(),
        orderable=False,
    )
    pause_reason = Column(
        verbose_name=_("Årsag til pause"),
        orderable=True,
        default="-",
    )
    pause_note = Column(
        verbose_name=_("Seneste notat"),
        empty_values=(),
        orderable=False,
    )

    def render_pause_start_date(self, value, record):
        last_change = record.last_change("paused")
        return last_change.date() if last_change else "-"

    def render_pause_note(self, value, record):
        last_note = (
            Note.objects.filter(
                personyear__person__pk=record.pk,
                text__icontains="udbetalingspause",
            )
            .order_by("-created")
            .first()
        )
        if not last_note:
            return "-"
        parts = last_note.text.split("\n")
        return parts[-1].strip()


class CPRFilter(Filter):
    field_class = CPRField

    def __init__(self, *args, **kwargs):
        kwargs.setdefault(
            "widget",
            forms.TextInput(
                attrs={
                    "class": "form-control form-control-sm",  # smaller input
                    "style": "max-width: 250px;",  # limits width
                }
            ),
        )
        super().__init__(*args, **kwargs)


class PersonFilterSet(FilterSet):
    cpr = CPRFilter("_cpr", label=_("CPR-nummer"), required=True)


DEFAULT_ALLOW_PAUSE_FILTER = False
DEFAULT_SELF_STARTED_PAUSE_FILTER = False


class YearMonthMixin:
    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["year"] = self.year
        context_data["month"] = self.month
        return context_data

    @cached_property
    def year(self) -> int:
        try:
            return int(self.request.GET.get("year"))  # type: ignore[attr-defined]
        except (TypeError, ValueError):
            return timezone.now().year

    @cached_property
    def month(self) -> int:
        if self.year < timezone.now().year:
            return 12  # For past years, always use last month of year
        else:
            try:
                return int(self.request.GET.get("month"))  # type: ignore[attr-defined]
            except (TypeError, ValueError):
                return timezone.now().month


class PersonYearMonthMixin(YearMonthMixin):
    @cached_property
    def person_pk(self) -> int:
        return self.kwargs["pk"]  # type: ignore[attr-defined]

    @cached_property
    def person_year(self):
        if self.month < settings.MONTH_OF_FIRST_PAYOUT:
            personyear = get_object_or_404(
                PersonYear,
                year_id=self.year - 1,
                person_id=self.person_pk,
            )
        else:
            personyear = get_object_or_404(
                PersonYear,
                year_id=self.year,
                person_id=self.person_pk,
            )
        return personyear


class PersonSearchView(
    LoginRequiredMixin,
    PermissionsRequiredMixin,
    SingleTableMixin,
    ViewLogMixin,
    FilterView,
):
    model = Person
    table_class = PersonTable
    filterset_class = PersonFilterSet
    template_name = "suila/person_search.html"
    matomo_pagename = "Personsøgning"
    required_model_permissions = ["suila.view_person"]

    def get_queryset(self):
        qs = Person.filter_user_permissions(
            super().get_queryset(),
            self.request.user,  # type: ignore
            "view",
        )
        # Add zero-padded text version of CPR to ensure proper display and sorting
        qs = qs.annotate(_cpr=LPad(Cast("cpr", CharField()), 10, Value("0")))
        # Set initial sorting (can be overridden by user)
        qs = qs.order_by("_cpr")
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.log_view(context["table"].page.object_list.data)
        return context


class PersonPauseListView(
    LoginRequiredMixin,
    PermissionsRequiredMixin,
    SingleTableMixin,
    ViewLogMixin,
    FilterView,
):
    model = Person
    table_class = PersonPauseTable
    template_name = "suila/person_pause_list.html"
    matomo_pagename = "Person - pauseliste"

    required_model_permissions = [
        "suila.view_person",
    ]

    def get_queryset(self):
        qs = Person.objects.filter(paused=True, allow_pause=False).exclude(
            pause_reason__in=[PauseReasonChoices.DEATH, PauseReasonChoices.MISSING]
        )

        # Add zero-padded text version of CPR to ensure proper display and sorting
        qs = qs.annotate(_cpr=LPad(Cast("cpr", CharField()), 10, Value("0")))

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.log_view(context["table"].page.object_list.data)
        return context


class PersonMonthTable(Table):
    month = TemplateColumn(
        template_name="suila/table_columns/month.html",
        verbose_name=_("Måned"),
    )
    payout_date = TemplateColumn(
        template_name="suila/table_columns/payout_date.html",
        verbose_name=_("Forventet udbetalingsdato"),
    )
    benefit = TemplateColumn(
        template_name="suila/table_columns/benefit.html",
        verbose_name=_("Forventet beløb til udbetaling"),
    )
    status = TemplateColumn(
        template_name="suila/table_columns/status.html",
        verbose_name=_("Status"),
    )


@dataclass(frozen=True)
class RelevantPersonMonth:
    person_month: PersonMonth
    next_payout_date: date
    quarantine_weight: int


class PersonDetailView(
    LoginRequiredMixin,
    PermissionsRequiredMixin,

suila/suila/templates/suila/forms/annual_income_estimate_form.html
{# SPDX-FileCopyrightText: 2024 Magenta ApS <info@magenta.dk> #}
{# SPDX-License-Identifier: MPL-2.0 #}

{% load i18n %}
<form method="post" enctype="multipart/form-data" action="{% url 'suila:set_person_annual_income_estimate' pk=person_id %}">
  {% csrf_token %}
  
  <input type="hidden" name="person" value="{{ person_id }}"/>
  <input type="hidden" name="year" value="{{ year }}"/>
  <input type="hidden" name="month" value="{{ month }}"/>

  <div class="form-check">
    <input class="form-check-input" type="radio" name="income_option" id="automatic_estimate" checked>
    <label class="form-check-label" for="automatic_estimate">
      {% translate "Benyt automatisk estimeret årsindkomst" %}
    </label>
  </div>

  <div class="form-check">
    <input class="form-check-input" type="radio" name="income_option" id="manual_estimate">
    <label class="form-check-label" for="manual_estimate">
      {% translate "Benyt manuelt estimeret årsindkomst" %}
    </label>
  </div>

  <div class="mb-3 ms-4">
    <input type="number" name="annual_income_estimate" class="form-control"
           placeholder="{% translate 'Estimeret årsindkomst' %}" autocomplete="off"
           inputmode="numeric" pattern="\d*" required disabled>
  </div>

  <div class="mb-3">
    <label for="note" class="form-label">{% translate "Notat" %}*</label>
    <textarea name="note" id="note" class="form-control"
              rows="3" autocomplete="off" required></textarea>
  </div>
  
  {% file_formset manually_entered_income_formset "manually_entered_income_formset" %}

  <div class="text-end">
    <button type="submit" class="btn btn-primary">{% translate "Gem estimering" %}</button>
  </div>
</form>

<script nonce="{{ request.csp_nonce }}">
  $(function () {
    const $manualRadio = $('#manual_estimate');
    const $autoRadio = $('#automatic_estimate');
    const $incomeInput = $('input[name="annual_income_estimate"]');

    // Check manual radio button if manually_entered_income is not None
    // and prefill the input field with manually_entered_income value
    {% if manually_entered_income is not None %}
      $manualRadio.prop('checked', true);
      $incomeInput.val('{{ manually_entered_income|floatformat:0 }}');
    {% endif %}

    function toggleInput() {
      if ($manualRadio.is(':checked')) {
        $incomeInput.prop('disabled', false);
      } else {
        $incomeInput.prop('disabled', true).val('');
      }
    }

    toggleInput();
    $('input[name="income_option"]').on('change', toggleInput);

    $incomeInput.on('input', function () {
      let val = $(this).val().replace(/\D/g, '').slice(0, 10);
      $(this).val(val); // Allow max. 10 digits
    });
  });
</script>

suila/suila/templates/suila/forms/estimation_engine_form.html
{# SPDX-FileCopyrightText: 2024 Magenta ApS <info@magenta.dk> #}
{# SPDX-License-Identifier: MPL-2.0 #}

{% load i18n %}
<form method="post" enctype="multipart/form-data" action="{% url 'suila:update_estimation_engine' pk=person_year_id %}">
  {% csrf_token %}
  
  <input type="hidden" name="person" value="{{ person_id }}"/>
  <input type="hidden" name="preferred_estimation_engine_a_default" value="{{ engine_a }}"/>
  <input type="hidden" name="preferred_estimation_engine_u_default" value="{{ engine_u }}"/>

  <div class="mb-3">
    <label for="preferred_estimation_engine_a">{% translate "Vælg estimeringsmotor (A)" %}</label>
    <select name="preferred_estimation_engine_a" id="preferred_estimation_engine_a" class="form-select">
      {% for value, label in engine_choices %}
        <option value="{{ value }}" {% if value == engine_a %}selected{% endif %}>
          {% if value == engine_a %}&#10003;{% else %}&nbsp;&nbsp;&nbsp;{% endif %}{{ label }}
        </option>
      {% endfor %}
    </select>
  </div>
  <div class="mb-3">
    <label for="preferred_estimation_engine_u">{% translate "Vælg estimeringsmotor (U)" %}</label>
    <select name="preferred_estimation_engine_u" id="preferred_estimation_engine_u" class="form-select">
      {% for value, label in engine_choices %}
        <option value="{{ value }}" {% if value == engine_u %}selected{% endif %}>
          {% if value == engine_u %}&#10003;{% else %}&nbsp;&nbsp;&nbsp;{% endif %}{{ label }}
        </option>
      {% endfor %}
    </select>
  </div>
  <div class="mb-3">
    <label for="note" class="form-label">{% translate "Notat" %}*</label>
    <textarea name="note" id="note" class="form-control"
              rows="3" autocomplete="off" required></textarea>
  </div>
  {% file_formset estimation_engine_formset "estimation_engine_formset" %}  

  <div class="text-end">
    <button id="engine_form_submit_button" type="submit" class="btn btn-primary" disabled>{% translate "Gem" %} </button>
  </div>
</form>

<script nonce="{{ request.csp_nonce }}">
$(document).ready(function() {
  const $selectA = $('#preferred_estimation_engine_a');
  const $selectU = $('#preferred_estimation_engine_u');
  const $submitBtn = $('#engine_form_submit_button');

  const defaultA = $selectA.val();
  const defaultU = $selectU.val();

  function checkIfDefaults() {
    if ($selectA.val() === defaultA && $selectU.val() === defaultU) {
      $submitBtn.prop('disabled', true);
    } else {
      $submitBtn.prop('disabled', false);
    }
  }

  // Initial check
  checkIfDefaults();

  // Listen for changes
  $selectA.on('change', checkIfDefaults);
  $selectU.on('change', checkIfDefaults);
});
</script>

suila/suila/templates/suila/forms/pause_form.html
{# SPDX-FileCopyrightText: 2024 Magenta ApS <info@magenta.dk> #}
{# SPDX-License-Identifier: MPL-2.0 #}

{% load i18n %}
<form method="post" enctype="multipart/form-data" action="{% url 'suila:pause_person' pk=object.pk %}">
  {% csrf_token %}

  <input type="hidden" name="year" value="{{ year }}"/> 
  <input type="hidden" name="month" value="{{ month }}"/> 

  <div class="mb-3">
    <label class="form-label d-block">{% translate "Status på udbetalinger" %}</label>

    <div class="toggle-container d-flex w-100 rounded-pill overflow-hidden" id="pauseToggle" style="background: #d8d8d8; cursor: pointer;">
      <div class="toggle-option flex-fill text-center py-2 {% if not paused %}active{% endif %}" data-value="false">{% translate "I gang" %}</div>
      <div class="toggle-option flex-fill text-center py-2 {% if paused %}active{% endif %}" data-value="true">{% translate "På pause" %}</div>
    </div>
    <input type="hidden" name="paused" id="pausedInput" value="{% if paused %}true{% else %}false{% endif %}">
  </div> 

  {% if paused %}  
    <div class="mb-3 hidden" id="resume_payment_date_container">
      {% resume_payments_date_info_box %}
    </div>
  {% else %}  
    <div class="mb-3 hidden" id="pause_effect_date_container">
      {% pause_effect_date_info_box %}
    </div>
  {% endif %}

  {% if user|has_permissions:"suila.change_person" %}  
  <div class="mb-3 hidden" id="pause_reason_container">
      <label class="form-label d-block" for="pause_reason">{% translate "Begrundelse" %}*</label>
      <select name="pause_reason" id="pause_reason" class="form-select">
        <option value="">-</option>
        {% for value, label in pause_reasons %}
          <option value="{{ value }}" {% if value == pause_reason %}selected{% endif %}>
            {{ label }}
          </option>
        {% endfor %}
      </select>
  </div>
  <div class="form-check mb-3" id="allow_pause_container">
      <input class="form-check-input" type="checkbox" name="allow_pause" id="allow_pause" {% if allow_pause %} checked {% endif %}>
      <label class="form-check-label" for="allow_pause">
        {% translate "Borgeren kan sætte udbetalinger på pause og genoptage dem." %}
      </label>
  </div>

  <div class="mb-3">
    <label for="note" class="form-label">{% translate "Notat" %}*</label>
    <textarea name="note" id="note" class="form-control"
              rows="3" autocomplete="off" required></textarea>
  </div>
  {% file_formset pause_formset "pause_formset" %}  
  {% else %}
  <input type="hidden" name="allow_pause" value="{{ allow_pause }}"/> 
  {{ pause_formset.management_form }}
  {% endif %}

  <div class="text-end">
    <button type="submit" id="pause_form_submit_button" class="btn btn-primary">{% translate "Gem" %}</button>
  </div>
</form>


{{ send_eboks_letter_when_pausing|json_script:"sendLetterVar" }}

{% blocktranslate asvar pause_eboks_msg trimmed %}
Du er ved at sætte borgeren på pause uden at tillade borgeren at genoptage
udbetalinger. Dette medfører at et e-Boks brev bliver sendt til borgeren.
Er du sikker på, at du vil fortsætte?
{% endblocktranslate %}

<script nonce="{{ request.csp_nonce }}">
$(function() {
  const $toggle = $('#pauseToggle');
  const $selectPause = $('#pausedInput');
  const $selectAllowPause = $('[name=allow_pause]');
  const $selectAllowPauseContainer = $('#allow_pause_container');
  const $pauseReason = $('#pause_reason');
  const $pauseReasonContainer = $('#pause_reason_container');
  const $submitBtn = $('#pause_form_submit_button');

  const $resumePaymentDateContainer = $('#resume_payment_date_container');
  const $pauseEffectDateContainer = $('#pause_effect_date_container');

  const defaultPause = $selectPause.val();

  const getSelectAllowPauseValue = function() {
    return $selectAllowPause.is(':checkbox')
      ? $selectAllowPause.prop('checked')
      : $selectAllowPause.val() === "True";
  }
  const defaultAllowPause = getSelectAllowPauseValue();
  const defaultReason = $pauseReason.val();

  function checkIfDefaults() {
    const currentPause = $selectPause.val();
    const currentAllowPause = getSelectAllowPauseValue();
    const currentReason = $pauseReason.val();
    
    $submitBtn.prop(
      'disabled',
      currentPause === defaultPause &&
      currentAllowPause === defaultAllowPause &&
      currentReason === defaultReason
    );
  
    // Show/hide reason dropdown
    if (currentPause === "true") {  
      $pauseReasonContainer.show();
      $resumePaymentDateContainer.hide();
      $pauseEffectDateContainer.show();
      $selectAllowPauseContainer.show();
    } else {
      $pauseReasonContainer.hide();
      $resumePaymentDateContainer.show();
      $pauseEffectDateContainer.hide();
      $selectAllowPauseContainer.hide();
      $pauseReason.val(""); 
    }
  }

  // Initial check
  checkIfDefaults();

  // Watch for checkbox/hidden allow_pause changes
  $selectAllowPause.on('change', checkIfDefaults);

  // Watch for reason changes
  $pauseReason.on('change', checkIfDefaults);

  // Toggle click handler
  $toggle.on('click', '.toggle-option', function () {
    const $this = $(this);
    // UI highlight
    $toggle.find('.toggle-option').removeClass('active');
    $this.addClass('active');

    // Update hidden input value
    $selectPause.val($this.data('value')).trigger('change');
  });

  // Watch for pause changes
  $selectPause.on('change', checkIfDefaults);

  $submitBtn.on('click', function(e) {
    const currentPause = $selectPause.val();
    const currentAllowPause = getSelectAllowPauseValue();
    const isPausing = currentPause === "true";
    const reasonVisible = $pauseReasonContainer.is(':visible');
    const sendLetter = JSON.parse(document.getElementById("sendLetterVar").textContent);

    // Require reason only if pausing and container visible
    if (isPausing && reasonVisible && !$pauseReason.val()) {
      e.preventDefault();
      alert("{% translate 'Vælg en begrundelse for at sætte udbetalinger på pause.' %}");
      $pauseReason.focus();
      return;
    }

    // Ask confirmation if pausing without allow_pause when letter must be sent
    const changed = (
      currentPause !== defaultPause ||
      currentAllowPause !== defaultAllowPause
    );

    if (sendLetter && changed && isPausing && !currentAllowPause) {
      if (!confirm("{{ pause_eboks_msg }}")) {
        e.preventDefault();
        return;
      }
    }
  });
});
</script>