suila/login/urls.py
# SPDX-FileCopyrightText: 2024 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0

from typing import List

from django.urls import URLPattern, URLResolver, include, path
from django.views.generic import TemplateView
from django_mitid_auth.saml.views import AccessDeniedView
from login.views import (  # BeskLoginCallbackView,; BeskMitIDLoginView,
    BeskLoginView,
    LogoutView,
    MitIdErrorView,
    TwoFactorSetup,
)

app_name = "login"


urlpatterns: List[URLResolver | URLPattern] = [
    # path("mitid/login/", BeskMitIDLoginView.as_view(), name="login"),
    # path(
    #     "mitid/login/callback/", BeskLoginCallbackView.as_view(),
    #      name="login-callback"
    # ),
    path("mitid/", include("django_mitid_auth.urls", namespace="mitid")),
    path(
        "login",
        BeskLoginView.as_view(),
        name="login",
    ),
    path(
        "logout",
        LogoutView.as_view(),
        name="logout",
    ),
    path(
        "error/login-timeout/",
        AccessDeniedView.as_view(template_name="login/login_timeout.html"),
        name="login-timeout",
    ),
    path(
        "error/login-repeat/",
        AccessDeniedView.as_view(template_name="login/login_repeat.html"),
        name="login-repeat",
    ),
    path(
        "error/login-nocpr/",
        AccessDeniedView.as_view(template_name="login/login_no_cpr.html"),
        name="login-no-cpr",
    ),
    path(
        "error/login-mitid-error/",
        MitIdErrorView.as_view(),
        name="login-mitid-error",
    ),
    path(
        "error/login-failed/",
        AccessDeniedView.as_view(template_name="login/login_failed.html"),
        name="login-failed",
    ),
    path(
        "logged_out",
        TemplateView.as_view(template_name="login/logged_out.html"),
        name="logged_out",
    ),
    path("two_factor/setup", TwoFactorSetup.as_view(), name="two_factor_setup"),
]

suila/suila/urls.py
# SPDX-FileCopyrightText: 2024 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0

from typing import List

from django.urls import URLPattern, URLResolver, path

from suila.api import api
from suila.views import (
    CalculationParametersGraph,
    CalculationParametersListView,
    CalculatorView,
    EboksMessageView,
    EmbeddingTemplateView,
    GeneratedEboksMessageView,
    GraphView,
    PersonAnnualIncomeEstimateUpdateView,
    PersonDetailEboksPreView,
    PersonDetailEboksSendView,
    PersonDetailIncomeView,
    PersonDetailNotesAttachmentView,
    PersonDetailNotesView,
    PersonDetailView,
    PersonGraphView,
    PersonPauseListView,
    PersonPauseUpdateView,
    PersonSearchView,
    PersonTaxScopeHistoryView,
    PersonYearEstimationEngineUpdateView,
    RootView,
)

app_name = "suila"


urlpatterns: List[URLResolver | URLPattern] = [
    path("api/", api.urls, name="api"),
    path("", RootView.as_view(), name="root"),
    path("calculator/", CalculatorView.as_view(), name="calculator"),
    path("graph/", GraphView.as_view(), name="graph"),
    path(
        "faq/",
        EmbeddingTemplateView.as_view(template_name="suila/faq.html"),
        name="faq",
    ),
    path(
        "about/",
        EmbeddingTemplateView.as_view(template_name="suila/about.html"),
        name="about",
    ),
    path("persons/", PersonSearchView.as_view(), name="person_search"),
    path(
        "persons/forced_pause/",
        PersonPauseListView.as_view(),
        name="person_pause_overview",
    ),
    path("persons/<int:pk>/", PersonDetailView.as_view(), name="person_detail"),
    path("persons/<int:pk>/graph/", PersonGraphView.as_view(), name="person_graph"),
    path(
        "person_year/<int:pk>/engine/update",
        PersonYearEstimationEngineUpdateView.as_view(),
        name="update_estimation_engine",
    ),
    path(
        "persons/<int:pk>/income/",
        PersonDetailIncomeView.as_view(),
        name="person_detail_income",
    ),
    path(
        "persons/<int:pk>/notes/",
        PersonDetailNotesView.as_view(),
        name="person_detail_notes",
    ),
    path(
        "persons/<int:pk>/tax_scope_history/",
        PersonTaxScopeHistoryView.as_view(),
        name="person_tax_scope_history",
    ),
    path(
        "person/<int:pk>/pause/",
        PersonPauseUpdateView.as_view(),
        name="pause_person",
    ),
    path(
        "person/<int:pk>/set_annual_income/",
        PersonAnnualIncomeEstimateUpdateView.as_view(),
        name="set_person_annual_income_estimate",
    ),
    path(
        "note_attachments/<int:pk>/",
        PersonDetailNotesAttachmentView.as_view(),
        name="note_attachment",
    ),
    path(
        "persons/<int:pk>/eboks/",
        PersonDetailEboksPreView.as_view(),
        name="person_detail_eboks_preview",
    ),
    path(
        "persons/<int:pk>/eboks/send/",
        PersonDetailEboksSendView.as_view(),
        name="person_detail_eboks_send",
    ),
    path(
        "persons/<int:pk>/msg/<int:year>/<int:month>/<str:type>/",
        GeneratedEboksMessageView.as_view(),
        name="person_generated_message",
    ),
    path(
        "persons/<int:pk>/msg/",
        EboksMessageView.as_view(),
        name="person_existing_message",
    ),
    path(
        "calculation_parameters/",
        CalculationParametersListView.as_view(),
        name="calculation_parameters_list",
    ),
    path(
        "calculation_parameters/graph/",
        CalculationParametersGraph.as_view(),
        name="calculation_parameters_graph",
    ),
]

suila/suila/views.py
# SPDX-FileCopyrightText: 2024 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0
import itertools
import json
import logging
from dataclasses import dataclass
from datetime import date
from decimal import Decimal
from functools import cached_property
from math import ceil
from typing import Any, Iterable
from urllib.parse import urlencode

from common.fields import CPRField
from common.models import User
from common.utils import SuilaJSONEncoder, omit
from common.view_mixins import BaseGetFormView, ViewLogMixin
from dateutil.relativedelta import relativedelta
from django import forms
from django.conf import settings
from django.contrib import messages
from django.core.files.base import ContentFile
from django.core.management import call_command
from django.db import transaction
from django.db.models import CharField, F, IntegerChoices, QuerySet, Value
from django.db.models.functions import Cast, LPad
from django.forms.models import BaseInlineFormSet, fields_for_model, model_to_dict
from django.http import Http404, HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from django.template.defaultfilters import date as format_date
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.utils.formats import number_format
from django.utils.translation import gettext
from django.utils.translation import gettext_lazy as _
from django.utils.translation import gettext_noop, override
from django.views.decorators.clickjacking import xframe_options_sameorigin
from django.views.generic import DetailView, FormView, ListView, TemplateView
from django.views.generic.base import ContextMixin
from django.views.generic.detail import BaseDetailView
from django.views.generic.edit import UpdateView
from django_filters import Filter, FilterSet
from django_filters.views import FilterView
from django_tables2 import (
    BooleanColumn,
    Column,
    SingleTableMixin,
    Table,
    TemplateColumn,
)
from django_tables2.columns.linkcolumn import BaseLinkColumn
from django_tables2.utils import Accessor
from login.view_mixins import LoginRequiredMixin

from suila.data import engine_choices
from suila.dates import get_pause_effect_date, get_payment_date
from suila.forms import (
    CalculationParametersForm,
    CalculatorForm,
    ConfirmationForm,
    IncomeSignalFilterForm,
    NoteAttachmentFormSet,
    NoteForm,
    PauseForm,
    PersonAnnualIncomeEstimateForm,
    PersonYearEstimationEngineForm,
)
from suila.integrations.eboks.client import EboksClient
from suila.models import (
    BTaxPayment,
    Employer,
    IncomeType,
    ManagementCommands,
    MonthlyIncomeReport,
    Note,
    NoteAttachment,
    PauseReasonChoices,
    Person,
    PersonMonth,
    PersonYear,
    StandardWorkBenefitCalculationMethod,
    SuilaEboksMessage,
    TaxInformationPeriod,
    WorkingTaxCreditCalculationMethod,
    Year,
)
from suila.view_mixins import MustHavePersonYearMixin, PermissionsRequiredMixin

logger = logging.getLogger(__name__)


class RootView(LoginRequiredMixin, ViewLogMixin, TemplateView):
    template_name = "suila/root.html"

    def get(self, request, *args, **kwargs):
        self.log_view()
        return super().get(request, *args, **kwargs)


class NameColumn(BaseLinkColumn):
    def __init__(self, *args, **kwargs):
        linkify = dict(viewname="suila:person_detail", args=[Accessor("pk")])
        kwargs.setdefault("linkify", linkify)
        super().__init__(*args, **kwargs)


class PersonTable(Table):
    name = NameColumn(verbose_name=_("Navn"))
    cpr = Column(
        accessor=Accessor("_cpr"),
        order_by=Accessor("_cpr"),
        verbose_name=_("CPR-nummer"),
        orderable=False,
        linkify=dict(viewname="suila:person_detail", args=[Accessor("pk")]),
    )
    full_address = Column(verbose_name=_("Adresse"))


class PersonPauseTable(Table):
    name = NameColumn(verbose_name=_("Navn"))
    cpr = Column(
        verbose_name=_("CPR-nummer"),
        orderable=True,
    )
    allow_pause = BooleanColumn(
        verbose_name=_("Må selv genoptage udbetalinger"),
        orderable=True,
    )
    pause_start_date = Column(
        verbose_name=_("Startdato for udbetalingspause"),
        empty_values=(),
        orderable=False,
    )
    pause_reason = Column(
        verbose_name=_("Årsag til pause"),
        orderable=True,
        default="-",
    )
    pause_note = Column(
        verbose_name=_("Seneste notat"),
        empty_values=(),
        orderable=False,
    )

    def render_pause_start_date(self, value, record):
        last_change = record.last_change("paused")
        return last_change.date() if last_change else "-"

    def render_pause_note(self, value, record):
        last_note = (
            Note.objects.filter(
                personyear__person__pk=record.pk,
                text__icontains="udbetalingspause",
            )
            .order_by("-created")
            .first()
        )
        if not last_note:
            return "-"
        parts = last_note.text.split("\n")
        return parts[-1].strip()


class CPRFilter(Filter):
    field_class = CPRField

    def __init__(self, *args, **kwargs):
        kwargs.setdefault(
            "widget",
            forms.TextInput(
                attrs={
                    "class": "form-control form-control-sm",  # smaller input
                    "style": "max-width: 250px;",  # limits width
                }
            ),
        )
        super().__init__(*args, **kwargs)


class PersonFilterSet(FilterSet):
    cpr = CPRFilter("_cpr", label=_("CPR-nummer"), required=True)


DEFAULT_ALLOW_PAUSE_FILTER = False
DEFAULT_SELF_STARTED_PAUSE_FILTER = False


class YearMonthMixin:
    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["year"] = self.year
        context_data["month"] = self.month
        return context_data

    @cached_property
    def year(self) -> int:
        try:
            return int(self.request.GET.get("year"))  # type: ignore[attr-defined]
        except (TypeError, ValueError):
            return timezone.now().year

    @cached_property
    def month(self) -> int:
        if self.year < timezone.now().year:
            return 12  # For past years, always use last month of year
        else:
            try:
                return int(self.request.GET.get("month"))  # type: ignore[attr-defined]
            except (TypeError, ValueError):
                return timezone.now().month


class PersonYearMonthMixin(YearMonthMixin):
    @cached_property
    def person_pk(self) -> int:
        return self.kwargs["pk"]  # type: ignore[attr-defined]

    @cached_property
    def person_year(self):
        if self.month < settings.MONTH_OF_FIRST_PAYOUT:
            personyear = get_object_or_404(
                PersonYear,
                year_id=self.year - 1,
                person_id=self.person_pk,
            )
        else:
            personyear = get_object_or_404(
                PersonYear,
                year_id=self.year,
                person_id=self.person_pk,
            )
        return personyear


class PersonSearchView(
    LoginRequiredMixin,
    PermissionsRequiredMixin,
    SingleTableMixin,
    ViewLogMixin,
    FilterView,
):
    model = Person
    table_class = PersonTable
    filterset_class = PersonFilterSet
    template_name = "suila/person_search.html"
    matomo_pagename = "Personsøgning"
    required_model_permissions = ["suila.view_person"]

    def get_queryset(self):
        qs = Person.filter_user_permissions(
            super().get_queryset(),
            self.request.user,  # type: ignore
            "view",
        )
        # Add zero-padded text version of CPR to ensure proper display and sorting
        qs = qs.annotate(_cpr=LPad(Cast("cpr", CharField()), 10, Value("0")))
        # Set initial sorting (can be overridden by user)
        qs = qs.order_by("_cpr")
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.log_view(context["table"].page.object_list.data)
        return context


class PersonPauseListView(
    LoginRequiredMixin,
    PermissionsRequiredMixin,
    SingleTableMixin,
    ViewLogMixin,
    FilterView,
):
    model = Person
    table_class = PersonPauseTable
    template_name = "suila/person_pause_list.html"
    matomo_pagename = "Person - pauseliste"

    required_model_permissions = [
        "suila.view_person",
    ]

    def get_queryset(self):
        qs = Person.objects.filter(paused=True, allow_pause=False).exclude(
            pause_reason__in=[PauseReasonChoices.DEATH, PauseReasonChoices.MISSING]
        )

        # Add zero-padded text version of CPR to ensure proper display and sorting
        qs = qs.annotate(_cpr=LPad(Cast("cpr", CharField()), 10, Value("0")))

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.log_view(context["table"].page.object_list.data)
        return context


class PersonMonthTable(Table):
    month = TemplateColumn(
        template_name="suila/table_columns/month.html",
        verbose_name=_("Måned"),
    )
    payout_date = TemplateColumn(
        template_name="suila/table_columns/payout_date.html",
        verbose_name=_("Forventet udbetalingsdato"),
    )
    benefit = TemplateColumn(
        template_name="suila/table_columns/benefit.html",
        verbose_name=_("Forventet beløb til udbetaling"),
    )
    status = TemplateColumn(
        template_name="suila/table_columns/status.html",
        verbose_name=_("Status"),
    )


@dataclass(frozen=True)
class RelevantPersonMonth:
    person_month: PersonMonth
    next_payout_date: date
    quarantine_weight: int


class PersonDetailView(
    LoginRequiredMixin,
    PermissionsRequiredMixin,

suila/suila/templates/suila/person_detail.html
{# SPDX-FileCopyrightText: 2024 Magenta ApS <info@magenta.dk> #}
{# SPDX-License-Identifier: MPL-2.0 #}

{% extends "suila/person_detail_base.html" %}
{% load i18n %}
{% load static %}
{% load render_table from django_tables2 %}
{% load amount_tags %}

{% block breadcrumb %}
{% if user.is_authenticated and user|has_permissions:"suila.view_person,suila.view_personyear" %}
<li class="breadcrumb-item"><a href="{% url 'suila:person_search' %}">{% translate "Borgersøgning" %}</a></li>
{% endif %}
<li class="breadcrumb-item">{% translate "Mit overblik" %}</li>
{% endblock %}

{% block extra_headers %}
<link rel="stylesheet" href="{% static 'bootstrap-icons/font/bootstrap-icons.min.css' %}"/>
<script src="{% static 'suila/formset.js' %}" nonce="{{ request.csp_nonce }}"></script>
<script src="{% static 'suila/fileinput.js' %}" nonce="{{ request.csp_nonce }}"></script>
{% endblock %}

{% block person_data %}
<div class="row mt-2">
    <div class="d-flex align-items-stretch gap-2">
    {% if manually_entered_income %}
    {% if person_id %}
        {% manually_entered_income_info_box %}
    {% endif %}
    {% endif %}
    {% if paused %}
        {% pause_info_box %}
    {% endif %}
    {% if person.dead %}
        {% dead_info_box %}
    {% endif %}
    {% if person.missing %}
        {% missing_info_box %}
    {% endif %}
    {% if in_quarantine and quarantine_weight == 0 %}
        {% quarantine_info_box %}
    {% endif %}
    {% if estimation_engine_changed %}
        {% estimation_engine_info_box %}
    {% endif %}
    </div>
</div>

{% if show_next_payment and not year_in_past %}
    <div class="grid gap-3 mt-5">
        <div class="g-col-3 emphasis">
            <b>{% translate "Næste udbetalingsdato" %}</b>
            <h1 class="mt-3">{{ next_payout_date|date }}</h1>
        </div>
        <div class="g-col-3 emphasis">
            <b>{% translate "Næste forventede beløb til udbetaling" %}</b>
            <h1 class="mt-3">
                {% if paused or in_quarantine and quarantine_weight == 0 %}
                    {{ 0|format_amount }} <i class="bi bi-exclamation-triangle-fill"></i>
                {% else %}
                    {{ benefit_calculated|format_amount }}
                {% endif %}
            </h1>
        </div>
        <div class="g-col-3 emphasis">
            <b>
                {% blocktranslate trimmed with year=year %}
                    Forventet beløb til udbetaling for hele {{ year }}
                {% endblocktranslate %}
            </b>
            <h1 class="mt-3">{{ estimated_year_benefit|format_amount }}</h1>
        </div>
        <div class="g-col-3 emphasis">
            <b>{% translate "Forventet årsindkomst fra arbejde" %}</b>
            <h1 class="mt-3">
                {% if manually_entered_income %}
                    {{ manually_entered_income|format_amount }}
                    <i class="bi bi-exclamation-triangle-fill"></i>
                {% else %}
                    {{ estimated_year_result|format_amount }}
                {% endif %}
            </h1>
        </div>
    </div>
{% endif %}

<div class="row mt-3">
    <div class="col-md-12">
        <div class="explainer">

            <p>
            {% if not year_in_past %}
            {% blocktranslate trimmed %}
            "Mit overblik" er dit overblik over kommende og tidligere udbetalinger af Suila-tapit for indeværende år.
            {% endblocktranslate %}
            {% blocktranslate trimmed %}
            Her får du et overblik over de vigtigste beløb og datoer, og en oversigt over dine forventede månedlige
            Suila-tapit udbetalinger.
            {% endblocktranslate %}
            </p>
            <p>
            {% blocktranslate trimmed %}
            Bemærk, at beløbene er vejledende, og kan ændre sig helt frem til den endelige udbetaling.
            {% endblocktranslate %}
            {% else %}
            {% blocktranslate trimmed %}
            Her kan du få et overblik over dine udbetalinger af Suila-tapit for forgangne år.
            {% endblocktranslate %}
            {% endif %}
            </p>

            <p><b>{% translate "Modregning" %}</b></p>
            {% blocktranslate trimmed %}
            Hvis du har gæld til det offentlige, kan der ske modregning af op til en tredjedel af beløbet inden
            udbetaling. Modregning betyder, at du modtager et lavere beløb, fordi dele af beløbet er brugt til at
            afdrage på din gæld til det offentlige. Eventuelle modregninger fremgår ikke af oplysningerne her på siden.
            Er der sket modregning, vil du modtage brev herom i din e-Boks.
            {% endblocktranslate %}
            <p><b>{% translate "NemKonto" %}</b></p>
            {% blocktranslate trimmed %}
            Suila-tapit udbetales kun til NemKonto. Hvis du ikke har en NemKonto, skal du oprette en, før du kan få
            udbetalt Suila-tapit. Har du ikke en NemKonto, skal du rette henvendelse til din bank herom.
            {% endblocktranslate %}
        </div>
    </div>
</div>

<div class="grid gap-3 mt-5">
    <div class="g-col-12 sidebar">
        <h2 class="mb-3">{% translate "Bemærk!" %}</h2>
        <p>
            {% blocktranslate trimmed %}
            Der bliver kun foretaget udbetalinger, hvis Skattestyrelsen har modtaget signal fra arbejdsmarkedet i form
            af indberetning af løn fra arbejdsgivere, betalte B-skatter, indberetning af indhandling fra
            indhandlingssteder, eller oplysning om udloddet udbytte fra selskaber.
            {% endblocktranslate %}
        </p>
        <p>
            {% blocktranslate trimmed %}
            Du modtager ikke en udbetaling, hvis næste udbetalingsbeløb er mindre end 100 kr. Beløbet vil blive overført
            til næste måned.
            {% endblocktranslate %}
        </p>
        <h3>{% translate "Sæt udbetalinger på pause" %}</h3>
        <p>
            {% blocktranslate trimmed %}
            Hvis du ikke ønsker at modtage den månedlige udbetaling af Suila-tapit, har du nu
            mulighed for at sætte udbetalingerne på pause. Pausen varer, så længe du ønsker det.
            {% endblocktranslate %}
        </p>
        <p>
            {% blocktranslate trimmed %}
            Hvis du er berettiget, mister du ikke retten til Suila-tapit. Du modtager en
            årsopgørelse i august næste år, der viser, hvor meget Suila-tapit du har til
            gode eller har modtaget for meget.
            {% endblocktranslate %}
        </p>
    </div>
</div>

{% if person_id %}
{% if user|has_permissions:"suila.change_person" or can_pause  %}
<div class="row mt-5">
    <h2> Handlinger </h2>
</div>
<div class="row mt-3">
    <div class="d-flex align-items-center mb-3">
        {% if user|has_permissions:"suila.change_person" %}
        <div class="me-2">
            {% action_button _("Ændre årsindkomst") "edit" "annual_income_form" "suila/forms/annual_income_estimate_form.html" %}
        </div>
        {% endif %}
        {% if user|has_permissions:"suila.change_person" or can_pause  %}
        <div class="me-2">
            {% action_button _("Udbetalingspause") "swap_horiz" "pause_form" "suila/forms/pause_form.html" %}
        </div>
        {% endif %}
        {% if user|has_permissions:"suila.change_person" %}
        <div class="me-2">
            {% action_button _("Skift estimeringsmotor") "settings" "estimation_engine_form" "suila/forms/estimation_engine_form.html" %}
        </div>
        {% endif %}
        <div class="me-2">
        <div class="btn-group">
            <label class="btn btn-outline-primary action-btn-label">Vis år:</label>
            <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle action-btn" data-bs-toggle="dropdown" aria-expanded="false">
                {{ year }}
            </button>
                <ul class="dropdown-menu">
                    {% for available_year in available_years %}
                    <li><a class="dropdown-item" href="?year={{ available_year }}">{{ available_year}}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        </div>

    </div>
</div>
{% endif %}
{% endif %}


<div class="grid gap-3 mt-5">
    {% if user|has_permissions:"suila.view_note" %}
    <div class="g-col-4 jumbo">
        {% url "suila:person_detail_notes" pk=person.pk as person_notes_url %}
        {% jumbo_link person_notes_url _("Notater") "assignment" %}
    </div>
    <div class="g-col-4 jumbo">
        {% url "suila:person_detail_income" pk=person.pk as person_income_url %}
        {% jumbo_link person_income_url _("Mine signaler") "assignment" %}
    </div>
    <div class="g-col-4 jumbo">
        {% url "suila:person_graph" pk=person.pk as person_income_url %}
        {% jumbo_link person_income_url _("Mit estimerede Suila-tapit") "link" %}
    </div>
    {% else %}
    <div class="g-col-12 jumbo">
        {% url "suila:person_detail_income" pk=person.pk as person_income_url %}
        {% jumbo_link person_income_url _("Mine signaler - få information om beregningsgrundlaget for dit Suila-tapit") "assignment" %}
    </div>
    {% endif %}
    {% if user|has_permissions:"suila.view_eboksmessage" and user|has_permissions:"suila.create_eboksmessage" %}
    <div class="g-col-4 jumbo">
        {% url "suila:person_detail_eboks_send" pk=person.pk as person_eboks_url %}
        {% jumbo_link person_eboks_url _("Årsopgørelse") "assignment" %}
    </div>
    {% endif %}
    {% if user|has_permissions:"suila.view_eboksmessage" %}
    <div class="g-col-4 jumbo">
        {% url "suila:person_detail_eboks_preview" pk=person.pk as person_eboks_preview_url %}
        {% jumbo_link person_eboks_preview_url _("e-Boks-beskeder preview") "assignment" %}
    </div>
    {% endif %}
    {% if user|has_permissions:"suila.view_person" %}
    <div class="g-col-4 jumbo">
        {% url "suila:person_tax_scope_history" pk=person.pk as person_tax_scope_history_url %}
        {% jumbo_link person_tax_scope_history_url _("Mandtal") "assignment" %}
    </div>
    {% endif %}
</div>

<div class="grid gap-5 my-5">
    <div class="g-col-9">
        <h1>
            {% blocktranslate trimmed with year=year %}
            Udbetalinger for {{ year }}
            {% endblocktranslate %}
        </h1>
        <div class="mt-3">
            {% render_table table %}
        </div>
    </div>
    <div class="g-col-3 sidebar">
        <h2 class="mb-5">{% translate "Information" %}</h2>
        <h3 class="my-3">{% translate "Forventet udbetalingsdato" %}</h3>
        <p class="mt-3">
            {% blocktranslate trimmed %}
            Suila-tapit udbetales d. 3. tirsdag i måneden. Udbetalingen er altid for indkomster to måneder forinden.
            Fx får du kun udbetalt Suila-tapit den 3. tirsdag i maj, hvis Skattestyrelsen har modtaget signal fra
            arbejdsmarkedet for marts måned.
            {% endblocktranslate %}
        </p>
        <h3 class="mt-5 mb-3">{% translate "Forventet beløb til udbetaling" %}</h3>
        <p class="mt-3">
            {% blocktranslate trimmed %}
            Det forventede beløb til udbetaling er baseret på din estimerede årsindkomst. Din estimerede årsindkomst
            genberegnes hver gang, Skattestyrelsen modtager nye oplysninger. Fx hvis en arbejdsgiver indsender
            lønoplysninger. Bemærk, at Skattestyrelsen kan foretage modregning på op til en tredjedel af det udbetalte
            beløb, hvis du har gæld til det offentlige.
            {% endblocktranslate %}
        </p>
        <h3 class="mt-5 mb-3">{% translate "Forklaring af statusbeskeder" %}</h3>
        <ul>
            <li>
                {% blocktranslate trimmed %}
                Beløb fastlagt. Din årsindkomst er estimeret, og der er fastlagt beløb for din kommende Suila-tapit
                udbetaling.
                {% endblocktranslate %}
            </li>
            <li>
                {% blocktranslate trimmed %}
                Sendt til udbetaling: Din Suila-tapit udbetaling er sendt til din NemKonto.
                {% endblocktranslate %}
            </li>
            <li>
                {% blocktranslate trimmed %}
                Udbetaling gennemført: Udbetalingen af Suila-tapit for den pågældende måned er afsluttet.
                {% endblocktranslate %}
            </li>
            <li>
                {% blocktranslate trimmed %}
                Fejl i udbetaling: Der er opstået en fejl under udbetaling af din Suila-tapit. Kontakt Skattestyrelsen
                for yderligere information.
                {% endblocktranslate %}
            </li>
            <li>
                {% blocktranslate trimmed %}
                Udbetalingspause: Der er ikke udbetalt Suila-tapit denne måned, da dine udbetalinger har været sat på pause af dig selv eller Skattestyrelsen.
                {% endblocktranslate %}
            </li>
        </ul>
    </div>
</div>
{% endblock %}