suila/data_update/urls.py
# SPDX-FileCopyrightText: 2024 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0


from data_update.views import (
    AnnualIncomeCreateView,
    AnnualIncomeUpdateView,
    MonthlyIncomeCreateView,
    MonthlyIncomeUpdateView,
    PersonMonthCreateView,
    PersonMonthView,
    PersonView,
    PersonYearAssessmentCreateView,
    PersonYearAssessmentUpdateView,
    PersonYearCreateView,
    PersonYearView,
)
from django.urls import URLPattern, URLResolver, path

app_name = "data_update"


urlpatterns: list[URLResolver | URLPattern] = [
    path("person/<str:cpr>", PersonView.as_view(), name="person_view"),
    path(
        "person/<str:cpr>/<int:year>",
        PersonYearView.as_view(),
        name="personyear_view",
    ),
    path(
        "person/<str:cpr>/create_year",
        PersonYearCreateView.as_view(),
        name="personyear_create",
    ),
    path(
        "person/<str:cpr>/<int:year>/<int:month>",
        PersonMonthView.as_view(),
        name="personmonth_view",
    ),
    path(
        "person/<str:cpr>/<int:year>/create_month",
        PersonMonthCreateView.as_view(),
        name="personmonth_create",
    ),
    path(
        "person/<str:cpr>/<int:year>/report/<int:pk>",
        AnnualIncomeUpdateView.as_view(),
        name="annualincome_update",
    ),
    path(
        "person/<str:cpr>/<int:year>/report/create",
        AnnualIncomeCreateView.as_view(),
        name="annualincome_create",
    ),
    path(
        "person/<str:cpr>/<int:year>/assessment/<int:pk>",
        PersonYearAssessmentUpdateView.as_view(),
        name="personyear_assessment_update",
    ),
    path(
        "person/<str:cpr>/<int:year>/assessment/create",
        PersonYearAssessmentCreateView.as_view(),
        name="personyear_assessment_create",
    ),
    path(
        "person/<str:cpr>/<int:year>/<int:month>/report/create",
        MonthlyIncomeCreateView.as_view(),
        name="monthlyincome_create",
    ),
    path(
        "person/<str:cpr>/<int:year>/<int:month>/report/<int:pk>",
        MonthlyIncomeUpdateView.as_view(),
        name="monthlyincome_update",
    ),
]

suila/login/urls.py
# SPDX-FileCopyrightText: 2024 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0

from typing import List

from django.urls import URLPattern, URLResolver, include, path
from django.views.generic import TemplateView
from django_mitid_auth.saml.views import AccessDeniedView
from login.views import (  # BeskLoginCallbackView,; BeskMitIDLoginView,
    BeskLoginView,
    LogoutView,
    MitIdErrorView,
    TwoFactorSetup,
)

app_name = "login"


urlpatterns: List[URLResolver | URLPattern] = [
    # path("mitid/login/", BeskMitIDLoginView.as_view(), name="login"),
    # path(
    #     "mitid/login/callback/", BeskLoginCallbackView.as_view(),
    #      name="login-callback"
    # ),
    path("mitid/", include("django_mitid_auth.urls", namespace="mitid")),
    path(
        "login",
        BeskLoginView.as_view(),
        name="login",
    ),
    path(
        "logout",
        LogoutView.as_view(),
        name="logout",
    ),
    path(
        "error/login-timeout/",
        AccessDeniedView.as_view(template_name="login/login_timeout.html"),
        name="login-timeout",
    ),
    path(
        "error/login-repeat/",
        AccessDeniedView.as_view(template_name="login/login_repeat.html"),
        name="login-repeat",
    ),
    path(
        "error/login-nocpr/",
        AccessDeniedView.as_view(template_name="login/login_no_cpr.html"),
        name="login-no-cpr",
    ),
    path(
        "error/login-mitid-error/",
        MitIdErrorView.as_view(),
        name="login-mitid-error",
    ),
    path(
        "error/login-failed/",
        AccessDeniedView.as_view(template_name="login/login_failed.html"),
        name="login-failed",
    ),
    path(
        "logged_out",
        TemplateView.as_view(template_name="login/logged_out.html"),
        name="logged_out",
    ),
    path("two_factor/setup", TwoFactorSetup.as_view(), name="two_factor_setup"),
]

suila/data_update/views.py
# SPDX-FileCopyrightText: 2024 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0
from data_update.forms import (
    ActionForm,
    AnnualIncomeCreateForm,
    AnnualIncomeForm,
    MonthlyIncomeCreateForm,
    MonthlyIncomeForm,
    PersonMonthCreateForm,
    PersonYearAssessmentCreateForm,
    PersonYearAssessmentForm,
    PersonYearCreateForm,
)
from django.core import management
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView, DetailView, FormView, UpdateView
from login.view_mixins import LoginRequiredMixin

from suila.estimation import EstimationEngine
from suila.models import (
    AnnualIncome,
    MonthlyIncomeReport,
    Person,
    PersonMonth,
    PersonYear,
    PersonYearAssessment,
)
from suila.view_mixins import PermissionsRequiredMixin


class PersonView(LoginRequiredMixin, PermissionsRequiredMixin, DetailView):
    model = Person
    template_name = "data_update/person.html"
    required_model_permissions = [
        "suila.view_person",
    ]

    def get_object(self, queryset=None):
        return Person.objects.get(
            cpr=self.kwargs["cpr"],
        )

    def get_context_data(self, **kwargs):
        return super().get_context_data(
            **{
                **kwargs,
                "person": self.object,
                "personyears": self.object.personyear_set.all(),
            }
        )


class PersonYearCreateView(LoginRequiredMixin, PermissionsRequiredMixin, CreateView):
    model = PersonYear
    form_class = PersonYearCreateForm
    required_model_permissions = [
        "suila.add_personyear",
    ]
    template_name = "data_update/personyear_create.html"

    def get_person(self):
        return Person.objects.get(cpr=self.kwargs["cpr"])

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["person"] = self.get_person()
        return kwargs

    def get_context_data(self, **kwargs):
        return super().get_context_data(**{**kwargs, "person": self.get_person()})

    def get_success_url(self):
        return reverse(
            "data_update:person_view",
            kwargs={"cpr": self.kwargs["cpr"]},
        )


class PersonYearView(
    LoginRequiredMixin, PermissionsRequiredMixin, DetailView, FormView
):
    model = PersonYear
    template_name = "data_update/personyear.html"
    form_class = ActionForm
    required_model_permissions = [
        "suila.view_personyear",
    ]

    def get_object(self, queryset=None):
        return PersonYear.objects.get(
            person__cpr=self.kwargs["cpr"],
            year_id=self.kwargs["year"],
        )

    def get_context_data(self, **kwargs):
        return super().get_context_data(
            **{
                **kwargs,
                "person": self.object.person,
                "personyear": self.object,
                "months": self.object.personmonth_set.all().order_by("month"),
                "annualincomes": self.object.annual_income_statements.all(),
                "assessments": self.object.assessments.all(),
            }
        )

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        action = form.cleaned_data["action"]
        if action == "estimate":
            EstimationEngine.estimate_all(
                self.object.year_id, self.object.person_id, count=None, dry_run=False
            )
            management.call_command(
                "autoselect_estimation_engine",
                year=self.object.year_id
                + 1,  # Will look at this year to set engine for next year
                cpr=self.object.person.cpr,
            )
        if action == "calculate":
            person_months = PersonMonth.objects.filter(
                person_year__year__year=self.object.year_id,
                person_year__person__cpr=self.object.person.cpr,
            )
            for person_month in person_months:
                management.call_command(
                    "calculate_benefit",
                    self.object.year_id,
                    person_month.month,
                    cpr=self.object.person.cpr,
                )
        return redirect(
            "data_update:personyear_view",
            cpr=self.object.person.cpr,
            year=self.object.year_id,
        )


class PersonYearSubView:
    template_name: str | None = "data_update/personyear_sub.html"

    def get_person_year(self):
        return PersonYear.objects.get(
            person__cpr=self.kwargs["cpr"],
            year_id=self.kwargs["year"],
        )

    def get_context_data(self, **kwargs):
        person_year = self.get_person_year()
        return super().get_context_data(
            **{
                **kwargs,
                "person": person_year.person,
                "personyear": person_year,
            }
        )

    def get_success_url(self):
        return reverse(
            "data_update:personyear_view",
            kwargs={"cpr": self.kwargs["cpr"], "year": self.kwargs["year"]},
        )


class PersonYearSubCreateView(PersonYearSubView):

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["person_year"] = self.get_person_year()
        return kwargs


class PersonMonthCreateView(
    LoginRequiredMixin, PermissionsRequiredMixin, PersonYearSubCreateView, CreateView
):
    model = PersonMonth
    form_class = PersonMonthCreateForm
    required_model_permissions = [
        "suila.add_personmonth",
    ]


class AnnualIncomeCreateView(
    LoginRequiredMixin, PermissionsRequiredMixin, PersonYearSubCreateView, CreateView
):
    model = AnnualIncome
    form_class = AnnualIncomeCreateForm
    required_model_permissions = [
        "suila.add_annualincome",
    ]


class PersonYearAssessmentCreateView(
    LoginRequiredMixin, PermissionsRequiredMixin, PersonYearSubCreateView, CreateView
):
    model = PersonYearAssessment
    form_class = PersonYearAssessmentCreateForm
    required_model_permissions = [
        "suila.add_personyearassessment",
    ]


class PersonYearAssessmentUpdateView(
    LoginRequiredMixin, PermissionsRequiredMixin, PersonYearSubView, UpdateView
):
    required_model_permissions = [
        "suila.view_personyearassessment",
        "suila.change_personyearassessment",
    ]
    form_class = PersonYearAssessmentForm
    model = PersonYearAssessment


class PersonMonthView(LoginRequiredMixin, PermissionsRequiredMixin, DetailView):
    model = PersonMonth
    template_name = "data_update/personmonth.html"
    required_model_permissions = [
        "suila.view_personmonth",
    ]

    def get_object(self, queryset=None):
        return PersonMonth.objects.get(
            person_year__person__cpr=self.kwargs["cpr"],
            person_year__year_id=self.kwargs["year"],
            month=self.kwargs["month"],
        )

    def get_context_data(self, **kwargs):
        return super().get_context_data(
            **{
                **kwargs,
                "person": self.object.person,
                "personyear": self.object.person_year,
                "incomereports": self.object.monthlyincomereport_set.all(),
            }
        )


class AnnualIncomeUpdateView(LoginRequiredMixin, PermissionsRequiredMixin, UpdateView):
    required_model_permissions = [
        "suila.view_annualincome",
        "suila.change_annualincome",
    ]
    form_class = AnnualIncomeForm
    model = AnnualIncome
    template_name = "data_update/annualincome.html"

    def get_context_data(self, **kwargs):
        return super().get_context_data(
            **{
                **kwargs,
                "person": self.object.person_year.person,
                "personyear": self.object.person_year,
            }
        )

    def get_success_url(self):
        return reverse(
            "data_update:personyear_view",
            kwargs={
                "cpr": self.object.person_year.person.cpr,
                "year": self.object.person_year.year,
            },
        )


class MonthlyIncomeCreateView(LoginRequiredMixin, PermissionsRequiredMixin, CreateView):
    required_model_permissions = [
        "suila.view_monthlyincomereport",
        "suila.change_monthlyincomereport",
    ]
    form_class = MonthlyIncomeCreateForm
    model = MonthlyIncomeReport
    template_name = "data_update/monthlyincome_create.html"

    def get_person_month(self):
        return PersonMonth.objects.get(
            person_year__person__cpr=self.kwargs["cpr"],
            person_year__year_id=self.kwargs["year"],
            month=self.kwargs["month"],
        )

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["person_month"] = self.get_person_month()
        return kwargs

    def get_context_data(self, **kwargs):
        person_month = self.get_person_month()
        return super().get_context_data(
            **{
                **kwargs,
                "person": person_month.person_year.person,
                "personyear": person_month.person_year,
                "personmonth": person_month,
            }
        )

    def get_success_url(self):
        person_month = self.get_person_month()
        return reverse(
            "data_update:personmonth_view",
            kwargs={
                "cpr": person_month.person.cpr,
                "year": person_month.person_year.year,
                "month": person_month.month,
            },
        )


class MonthlyIncomeUpdateView(LoginRequiredMixin, PermissionsRequiredMixin, UpdateView):
    required_model_permissions = [
        "suila.view_monthlyincomereport",
        "suila.change_monthlyincomereport",
    ]
    form_class = MonthlyIncomeForm
    model = MonthlyIncomeReport
    template_name = "data_update/monthlyincome_update.html"

    def get_context_data(self, **kwargs):

suila/data_update/templates/data_update/annualincome.html
{# SPDX-FileCopyrightText: 2025 Magenta ApS <info@magenta.dk> #}
{# SPDX-License-Identifier: MPL-2.0 #}
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
</head>
<body>
<p>
<a href="{% url 'data_update:person_view' cpr=person.cpr %}">{{ person.cpr }}</a> >
<a href="{% url 'data_update:personyear_view' cpr=person.cpr year=personyear.year %}">{{ personyear.year }}</a> >
Årsindkomst
</p>

<form method="post">
    {% csrf_token %}
    <table class="table">
    {{ form.as_table }}
    </table>
    <button type="submit" class="btn btn-primary">Gem</button>
</form>
</body>
</html>

suila/data_update/templates/data_update/monthlyincome_create.html
{# SPDX-FileCopyrightText: 2025 Magenta ApS <info@magenta.dk> #}
{# SPDX-License-Identifier: MPL-2.0 #}
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
</head>
<body>
<a href="{% url 'data_update:person_view' cpr=person.cpr %}">{{ person.cpr }}</a> >
<a href="{% url 'data_update:personyear_view' cpr=person.cpr year=personyear.year %}">{{ personyear.year }}</a> >
<a href="{% url 'data_update:personmonth_view' cpr=person.cpr year=personyear.year month=personmonth.month %}">{{ personmonth.month }}</a> >
Opret
<form method="post" action="">
    {% csrf_token %}
    <table class="table">
    {{ form.as_table }}
    </table>
    <button type="submit" class="btn btn-primary">Gem</button>
</form>
</body>
</html>

suila/data_update/templates/data_update/monthlyincome_update.html
{# SPDX-FileCopyrightText: 2025 Magenta ApS <info@magenta.dk> #}
{# SPDX-License-Identifier: MPL-2.0 #}
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
</head>
<body>
<a href="{% url 'data_update:person_view' cpr=person.cpr %}">{{ person.cpr }}</a> >
<a href="{% url 'data_update:personyear_view' cpr=person.cpr year=personyear.year %}">{{ personyear.year }}</a> >
<a href="{% url 'data_update:personmonth_view' cpr=person.cpr year=personyear.year month=personmonth.month %}">{{ personmonth.month }}</a> >
{{ object.pk }}
<form method="post" action="">
    {% csrf_token %}
    <table class="table">
    {{ form.as_table }}
    </table>
    <button type="submit" class="btn btn-primary">Gem</button>
</form>
</body>
</html>

suila/data_update/templates/data_update/person.html
{# SPDX-FileCopyrightText: 2025 Magenta ApS <info@magenta.dk> #}
{# SPDX-License-Identifier: MPL-2.0 #}
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
</head>
<body>
{{ person.cpr }}
<table class="table">
    <tr>
        <th>Year</th>
        <th></th>
    </tr>
    {% for year in personyears %}
    <tr>
        <td>{{ year.year }}</td>
        <td><a href="{% url 'data_update:personyear_view' cpr=object.cpr year=year.year %}">link</a></td>
    </tr>
    {% endfor %}
</table>
<a href="{% url 'data_update:personyear_create' cpr=object.cpr %}" class="btn btn-primary btn-sm">Opret år</a>
</body>
</html>

suila/data_update/templates/data_update/personmonth.html
{# SPDX-FileCopyrightText: 2025 Magenta ApS <info@magenta.dk> #}
{# SPDX-License-Identifier: MPL-2.0 #}
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
</head>
<body>
<p>
<a href="{% url 'data_update:person_view' cpr=person.cpr %}">{{ person.cpr }}</a> >
<a href="{% url 'data_update:personyear_view' cpr=person.cpr year=personyear.year %}">{{ personyear.year }}</a> >
{{ object.month }}
</p>

<h3>Månedsindtægter</h3>
<table class="table">
    <tr>
        <th>Employer</th>
        <th>a_income</th>
        <th>b_income</th>
        <th>u_income</th>
        <th></th>
    </tr>
    {% for incomereport in incomereports %}
    <tr>
        <td>{{ incomereport.employer.cvr }}</td>
        <td>{{ incomereport.a_income }}</td>
        <td>{{ incomereport.b_income }}</td>
        <td>{{ incomereport.u_income }}</td>
        <td><a href="{% url 'data_update:monthlyincome_update' cpr=person.cpr year=object.year month=object.month pk=incomereport.pk %}">link</a></td>
    </tr>
    {% endfor %}
</table>
<a href="{% url 'data_update:monthlyincome_create' cpr=person.cpr year=object.year month=object.month  %}" class="btn btn-primary btn-sm">Opret</a>
</body>
</html>

suila/data_update/templates/data_update/personyear.html
{# SPDX-FileCopyrightText: 2025 Magenta ApS <info@magenta.dk> #}
{# SPDX-License-Identifier: MPL-2.0 #}
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
</head>
<body>
<p>
<a href="{% url 'data_update:person_view' cpr=person.cpr %}">{{ person.cpr }}</a> >
{{ object.year }}
</p>

<h3>Måneder</h3>
<table class="table table-bordered">
    <thead>
    <tr>
        <th>Month</th>
        <th>amount_sum</th>
        <th></th>
    </tr>
    </thead>
<tbody>
    {% for month in months %}
    <tr>
        <td>{{ month.month }}</td>
        <td>{{ month.amount_sum }}</td>
        <td><a href="{% url 'data_update:personmonth_view' cpr=person.cpr year=object.year month=month.month %}">link</a></td>
    </tr>
    {% endfor %}
</tbody>
</table>
<a href="{% url 'data_update:personmonth_create' cpr=person.cpr year=object.year %}" class="btn btn-primary btn-sm">Opret ny</a>


{#<hr/>#}
{##}
{#<h3>Årsindtægter</h3>#}
{#<table class="table table-bordered">#}
{#    <tr>#}
{#        <th></th>#}
{#    </tr>#}
{#    {% for annualincome in annualincomes %}#}
{#        <tr>#}
{#            <td><a href="{% url 'data_update:annualincome_update' cpr=person.cpr year=object.year pk=annualincome.pk %}">link</a></td>#}
{#        </tr>#}
{#    {% endfor %}#}
{#</table>#}
{#<a href="{% url 'data_update:annualincome_create' cpr=person.cpr year=object.year %}" class="btn btn-primary btn-sm">Opret ny</a>#}

<hr/>

<h3>Forskudsopgørelser</h3>
<table class="table table-bordered">
    <tr>
        <th>Valid_from</th>
        <th></th>
    </tr>
    {% for assessment in assessments %}
        <tr>
            <td>{{ assessment.valid_from }}</td>
            <td><a href="{% url 'data_update:personyear_assessment_update' cpr=person.cpr year=object.year pk=assessment.pk %}">link</a></td>
        </tr>
    {% endfor %}
</table>
<a href="{% url 'data_update:personyear_assessment_create' cpr=person.cpr year=object.year %}" class="btn btn-primary btn-sm">Opret ny</a>

<hr/>
<form method="post">
    {% csrf_token %}
    <button class="btn btn-primary" type="submit" name="{{ form.action.name }}" value="estimate">Estimér</button>
    <button class="btn btn-primary" type="submit" name="{{ form.action.name }}" value="calculate">Beregn tilskud</button>
</form>
</body>
</html>

suila/data_update/templates/data_update/personyear_create.html
{# SPDX-FileCopyrightText: 2025 Magenta ApS <info@magenta.dk> #}
{# SPDX-License-Identifier: MPL-2.0 #}
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
</head>
<body>
<p>
<a href="{% url 'data_update:person_view' cpr=person.cpr %}">{{ person.cpr }}</a> >
Opret
</p>

<form method="post">
    {% csrf_token %}
    <table class="table">
    {{ form.as_table }}
    </table>
    <button type="submit" class="btn btn-primary">Gem</button>
</form>
</body>
</html>

suila/data_update/templates/data_update/personyear_sub.html
{# SPDX-FileCopyrightText: 2025 Magenta ApS <info@magenta.dk> #}
{# SPDX-License-Identifier: MPL-2.0 #}
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
</head>
<body>
<p>
<a href="{% url 'data_update:person_view' cpr=person.cpr %}">{{ person.cpr }}</a> >
<a href="{% url 'data_update:personyear_view' cpr=person.cpr year=personyear.year %}">{{ personyear.year }}</a> >
Opret
</p>

<form method="post">
    {% csrf_token %}
    <table class="table">
    {{ form.as_table }}
    </table>
    <button type="submit" class="btn btn-primary">Gem</button>
</form>
</body>
</html>